### ISSUE TITLE
GNOME Project whitelist status

### ISSUE THREAD

**Issue by averi** [openstreetmap/operations#738]
Hi,

the GNOME Infrastructure has a whitelist with OSM which was agreed on several years ago. What we're however noticing is that the rate limit is still applied to our OSM proxy and that makes the proxy fail to forward additional requests, would you mind verifying you have these IPs (IPv4 + IPv6) defined on your firewall:

8.43.85.3,8.43.85.4,8.43.85.5
AND
2620:52:3:1:5054:ff:fe0a:75a4, 2620:52:3:1:5054:ff:fe0a:75a2, 2620:52:3:1:5054:ff:fe0a:75aa

Thanks!

**Comment by averi** [comment]
An excerpt of a failed reverse proxy request:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=53.10403&lon=23.17019&addressdetails=1&accept-language=en-US&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff33470b9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

**Comment by tomhughes** [comment]
@lonvia?

**Comment by lonvia** [comment]
We only had the IPv4 addresses. I've added the IPv6 ones. It will take a couple of hours to deploy the change and then have the servers unbanned.

**Comment by averi** [comment]
Thank you!

**Comment by Firefishy** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/22076001213b1d8d27763c787ffc125931c7c164
Feel free to re-open if there is still and issue.

**Comment by averi** [comment]
Seems the issue is still there:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=xxx&lon=xxx&addressdetails=1&accept-language=en-IN&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8de80b2d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
ERROR:    Exception in ASGI application
```

Do you see any IP address in the 8.43.85.0/24 range on your blacklist?

**Comment by averi** [comment]
Seems I have no way to re-open this, please do if you can, thanks!

**Comment by tomhughes** [comment]
I can't see that address in the logs on any of the servers - do you know which server you are hitting?

**Comment by averi** [comment]
We're hitting corvallis.nominatim.openstreetmap.org much likely, the mail address associated with the queries is zeeshanak (AT gnome.org).

**Comment by lonvia** [comment]
Your IPs are not banned on any of the servers and I see requests hitting corvallis.

With an error message of `Network is unreachable`, it is much more likely that there is a problem with network configuration on your side.

**Comment by averi** [comment]
Ack, will keep looking, thanks!
