### ISSUE TITLE
Remove OPVNKarte from featured layers list

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#907]
As decided last ops meeting

- [ ] Remove from website
- [ ] Remove from matomo as target?

**Comment by 1ec5** [comment]
Should we also remove OPVNKarte from the wiki’s Kartographer configuration?

/cc @Tigerfell

**Comment by Firefishy** [comment]
ÖPNVKarte tile server `tileserver.memomaps.de` occasionally responses with an expired certificate.

```
Certificate chain
 0 s:CN = tile.memomaps.de
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Apr  2 17:03:50 2023 GMT; NotAfter: Jul  1 17:03:49 2023 GMT
```

**Comment by Firefishy** [comment]
OPVNKarte seems to be fast and responsive again. The certificate issue seems to have been resolved. Unsure how current the site data is.

**Comment by SomeoneElseOSM** [comment]
> Unsure how current the site data is.
With regard to that point only - within 6 days at least - a change by me 6 days ago to https://www.openstreetmap.org/node/3189208227/history is there.

**Comment by grischard** [comment]
It's strange - https://www.xn--pnvkarte-m4a.de/#6.2747;49.5049;18 doesn't reflect the changes 8 days ago in https://www.openstreetmap.org/changeset/138997711 and still shows the old name on https://www.openstreetmap.org/node/443657960 etc.

I suggest keeping them on watch for now, and revisiting the issue in a month.

**Comment by patrickov** [comment]
Hi, I'd like to testify that the layer seems to be working again since last week, and recent edits (mostly) appear.

There are, of course, oddities.  From what I see, I think the layer was developed to have specific rules for updating.  If a tile doesn't feature anything actually altering the rendering it won't update,

For example, you can notice the labelling discrepancies in the below link.  I guess the tile in the centre was updated but not the one to its left, most likely because there's nothing to update the rendering there (far too many bus routes in the area to make labelling fit in already)

https://www.openstreetmap.org/#map=18/22.31513/114.23618&layers=O

**Comment by Kovoschiz** [comment]
Specifically https://tileserver.memomaps.de/tilegen/18/214255/114395.png and https://tileserver.memomaps.de/tilegen/18/214255/114395.png   
![image](https://github.com/openstreetmap/operations/assets/11350903/7220bf2f-24ad-4ca1-a6f1-8ed8b252d380)
![image](https://github.com/openstreetmap/operations/assets/11350903/a8ced0f8-032d-47e1-8e4b-f24494909f0b)

**Comment by Firefishy** [comment]
OPVNKarte issues seem to be resolved. For now all good. If the issues crop up again this ticket can be re-opened or new ticket created as appropriate.

**Comment by grischard** [comment]
Broken again: https://tileserver.memomaps.de/tilegen/18/77232/98550.png

I suggest we drop them - they're broken more often than they reply to email.

**Comment by Firefishy** [comment]
The tileserver.memomaps.de certificate expired Sunday, 29 October 2023 at 23:23:24.

**Comment by mp747474** [comment]
It also seems that database replication of ÖPNVKarte has stopped again. We're getting more and more complaints (map notes etc.) of people who complain that their bus lines haven't been updated on the ÖPNVKarte.

**Comment by grischard** [comment]
The layer has been removed
